language: node_js

node_js:
  - 16

script:
  - npm run build

before_install:
  - sudo apt-get -y install nasm

addons:
  apt:
    update: true

deploy:
  - provider: s3
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET
    skip_cleanup: true
    bucket: dev.makeuc.io
    local_dir: ./public
    on:
      branch: dev

  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: ./public
    keep_history: true
    repo: MakeUC/makeuc.github.io
    target_branch: master
    fqdn: makeuc.io
    verbose: true
    on:
      branch: master
